### PR TITLE
[JENKINS-30512] use java API instead of ifconfig to lookup docker0 ipv4 address

### PR DESCRIPTION
**Pull request by ydubreuil**
This fixes [JENKINS-30512](https://issues.jenkins-ci.org/browse/JENKINS-30512). Previous implementation relied on parsing `ifconfig` output which changed on recent version. This implementation uses Java API to prevent parsing issues.

@reviewbybees

### CODE REVIEW

**Comment by ganthore** [comment]
Good job, now I can run this on RHEL7 and Gentoo without any problems! :+1:

**Comment by ydubreuil** [comment]
Great :) Can you give me your bee then?

**Comment by ganthore** [comment]
:bee:

**Comment by ydubreuil** [comment]
@reviewbybees done

**Pull request merged**
