### PR TITLE
JENKINS-66171: Failed to lookup the docker build ImageID

### PR DESCRIPTION
**Pull request by RealCLanger**
Previously we were capturing `docker build` output, which led to some problems:
1. Other programs could print similar strings, which would match but did not contain the image ID. This was fixed by taking the last capture as image ID.
2. `docker build` output has changed in version 23, so now we'd have to match the output twice. First pass for docker < 23, and another for >= 23

Docker has had the `--iidfile` option for some time now, so switch to using it. It is a much less fragile way to capture the image ID.

Tested with Docker 20.10.23 and 23.0.1

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by RealCLanger** [comment]
Another try, superseding #81 and #80, to catch attention.

**Comment by RealCLanger** [comment]
@jonhermansen Any updates?

**Comment by RealCLanger** [comment]
@jonhermansen Is it possible to merge this?

**Comment by JeremyMcCully** [comment]
We just ran into this issue after a Docker upgrade. Can this be merged?

**Comment by RealCLanger** [comment]
> We just ran into this issue after a Docker upgrade. Can this be merged?

That would be nice. However, unfortunately @jonhermansen is not reacting and I don't know whether there is somebody else who could move this forward.

**Comment by RealCLanger** [comment]
@jonhermansen @Vlatombe, any help or direction on this one? Would be really appreciated. Thanks.

**Comment by jonhermansen** [comment]
In the next few days I'll try to figure out how to push an update out to the plugin server. It's been quite a while since I've done it.

I took a much needed break from software this summer, so thank you all for waiting patiently. For those effected by the bug, I feel your pain! A similar bug is the whole reason I took up maintanership of this plugin in the first place.

Please know that you can, and have always been able to build a custom version of the plugin locally, and manually install the .jpi file into your own Jenkins instance. In fact, probably one thing I want to test before releasing is that we remain backwards compatible with old versions of Docker. The install base is pretty low, but having firsthand experience with plugins that inexplicably break on upgrade, I'd' rather help people avoid this pain in the future.

I've also made @RealCLanger a contributor on this repository to hopefully make changes like this more expedient in the future.

Thanks.

**Comment by RealCLanger** [comment]
> I took a much needed break from software this summer, so thank you all for waiting patiently. For those effected by the bug, I feel your pain! A similar bug is the whole reason I took up maintanership of this plugin in the first place.

Thanks for picking this up now. Hope your break went as positive as you expected or even better. 😄  Sorry for being annoying, maybe, but I didn't know and couldn't find anybody who could help out here.

> Please know that you can, and have always been able to build a custom version of the plugin locally, and manually install the .jpi file into your own Jenkins instance.
Yes, that was my workaround, but I had to fix this during every upgrade of our server in a manual process, so I'm hoping there will be an official version with the fix soon.

> In fact, probably one thing I want to test before releasing is that we remain backwards compatible with old versions of Docker. The install base is pretty low, but having firsthand experience with plugins that inexplicably break on upgrade, I'd' rather help people avoid this pain in the future.

There won't be a problem with older Docker versions that support --iidfile, I suspect. Even older ones where this support is not available will be broken, I guess. Not sure whether they are too old for being supported? If not, it'll need additional code to handle that case as well.

> I've also made @RealCLanger a contributor on this repository to hopefully make changes like this more expedient in the future.

Thanks, I already used my new powers to close #81.

> In the next few days I'll try to figure out how to push an update out to the plugin server. It's been quite a while since I've done it.

Please let me know if I can be of help here. If you want me to learn how to do it (e.g. enable me to create releases), please let me know. I also think that this plugin should be updated in a way that it is buildable with a JDK > 8, which doesn't seem to be the case currently.

Thanks
Christoph

**Comment by etherz10** [comment]
@RealCLanger @jonhermansen Given the latest plugin version available to easily install currently fails with the ImageID error I thought I'd give building the latest master a go but I'm getting the following errors when running `mvn clean package` -- Any guidance would be appreciated.


```
mvn -v
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.20.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-84-generic", arch: "amd64", family: "unix"
```

```
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ docker-custom-build-environment ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 22 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ docker-custom-build-environment ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /home/kieron/work/docker-custom-build-environment-plugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] java.nio.file.NoSuchFileException: /home/kieron/work/docker-custom-build-environment-plugin/target/classes/META-INF/annotations/hudson.Extension
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.446 s
[INFO] Finished at: 2023-10-10T14:30:15Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project docker-custom-build-environment: Compilation failure
[ERROR] java.nio.file.NoSuchFileException: /home/kieron/work/docker-custom-build-environment-plugin/target/classes/META-INF/annotations/hudson.Extension
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by RealCLanger** [comment]
@etherz10 I could get the master build working when building with a JDK8.

@jonhermansen What about the efforts to publish a new release?

**Comment by crackerjam** [comment]
Sorry to bother, but has there been any movement on this?  It seems functionality with recent versions of docker has been broken for at least a year now and a fix would be greatly appreciated.

**Pull request merged**
