### PR TITLE
[JENKINS-66171] Failed to lookup the docker build ImageID - Fix needed for Docker v23

### PR DESCRIPTION
**Pull request by RealCLanger**
This PR fixes handling of changed `docker build` output with docker v23. It also works for `docker build`in older versions.

With v23, the output of docker build is in stderr. The regex to get the hash of the image had to be adapted.

Issue fixed: https://issues.jenkins.io/browse/JENKINS-66171

I tested in my Jenkins instances with docker v23 and docker v20.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by ndeloof** [comment]
To avoid parsing console output with risk for such changes to have impacts, you should rely on `--iidfile` flag to store image build ID in a temporary file.
My 2 cents :)

**Comment by jonhermansen** [comment]
> To avoid parsing console output with risk for such changes to have impacts, you should rely on `--iidfile` flag to store image build ID in a temporary file. My 2 cents :)

100% agreed, capturing the "Successfully built" text was never a great practice. And it was also a problem if some process printed a similar string, before the Docker build had actually been completed.

I haven't touched this project in a long time, but I would like to help. Let me see if I can get it building on my end and I can manually test the change.

**Comment by jonhermansen** [comment]
I tried another approach in #81, @RealCLanger, what do you think? Should it also work for your case?

Maybe this way, the plugin can continue to work even if Docker changes output format again.

**Comment by jonhermansen** [comment]
@RealCLanger I'll wait for your results until I merge and release a new version, but no rush.

If needed you can always manually install your own plugin build through Jenkins settings.

**Pull request closed without merging**
