### PR TITLE
feature/custom_alpine_image

### PR DESCRIPTION
**Pull request by sc0rp1us**
**reason:**
origin plugin is able to work only on x86_64 platforms
because of hardcoded alpine linux string

**solution:**
the patch added a field which allows defining another alpine linux string
for example for ppc64le or arm64 platforms

### CODE REVIEW

**Comment by monester** [comment]
It is very important feature as default alpine unable to run on power8.

**Comment by jonhermansen** [comment]
Hi @sc0rp1us. I'm wondering... can we just change the default image used to something that would work on the platforms you need it to? It seems that docker images should be able to use the same name, but be cross-platform.

https://github.com/docker-library/official-images#multiple-architectures

**Comment by monester** [comment]
Even with this option you should specify architecture as mentioned on: https://github.com/multiarch/alpine
In plugin value 'alpine:3.2' is hardcoded and it can't run on power8 architecture.

```
root@ubuntu1604:~# docker run -ti alpine:3.2
panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"
root@ubuntu1604:~# docker --version
Docker version 1.12.6, build 78d1802
root@ubuntu1604:~# uname -a
Linux ubuntu1604 4.8.0-52-generic #55~16.04.1-Ubuntu SMP Fri Apr 28 14:33:04 UTC 2017 ppc64le ppc64le ppc64le GNU/Linu
```

**Comment by jonhermansen** [comment]
@monester Perhaps that is not an image that we want to use, because they are using different tags for different architectures. But from reading the docker-library documentation, it appears that we should be able to use the same image name across multiple platforms.

Debian and Ubuntu images allegedly support this but I haven't tested (no arm or ppc hosts around). I might give it a whirl under qemu to test with different slaves.

It looks like there is an alpine image in the works that might support this. https://github.com/gliderlabs/docker-alpine/pull/352

**Comment by jonhermansen** [comment]
> We strongly recommend that most images create a single Dockerfile per entry in the library file that can be used for multiple architectures. This means that each supported architecture will have the same FROM line (e.g. FROM debian:jessie).

**Comment by monester** [comment]
@jonhermansen I've just tested docker run alpine:3.6 on power8 and it is working. So I think upgrading version of alpine to 3.6 use it in docker-custom-build-environment-plugin would solve this issue.

**Comment by jonhermansen** [comment]
Thanks for your testing @monester! I don't mean to push back on adding a feature, but I do want to limit the available configuration options where possible.

@sc0rp1us Would this be an acceptable compromise? Just changing the alpine image to a later version? Can you try `docker run alpine:3.6` on one of your arm systems?

**Comment by sc0rp1us** [comment]
**aarch64**
```
~# docker run -it alpine:3.6 uname -a
Linux 63c808dc62ba 4.13.0-31.34-generic #34+yarmouth2.1-Ubuntu SMP Wed Jan 24 18:32:24 UTC 2018 aarch64 Linux
```
**ppc64le**
```
# docker run -ti alpine:3.6 uname -a
Linux f01d5584b3a5 4.8.0-52-generic #55~16.04.1-Ubuntu SMP Fri Apr 28 14:33:04 UTC 2017 ppc64le Linux
```

**Comment by jonhermansen** [comment]
Thanks again @monester and @sc0rp1us for your helping to test these changes!

**Comment by jonhermansen** [comment]
This is released in 1.7.3.

**Pull request closed without merging**
